//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBookPvt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customerTable()
        {
            this.bookOrderTables = new HashSet<bookOrderTable>();
            this.customerPaymentTables = new HashSet<customerPaymentTable>();
        }
    
        public int Id { get; set; }
        public string cusName { get; set; }
        public string cusEmail { get; set; }
        public string cusAddress { get; set; }
        public int cusPhone { get; set; }
        public string cusUsername { get; set; }
        public string cusPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bookOrderTable> bookOrderTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerPaymentTable> customerPaymentTables { get; set; }
    }
}
