//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBookPvt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerPaymentTable
    {
        public int Id { get; set; }
        public int cusIdFk { get; set; }
        public int bookOrderIdFk { get; set; }
        public Nullable<double> totalAmount { get; set; }
        public string date { get; set; }
    
        public virtual bookOrderTable bookOrderTable { get; set; }
        public virtual customerTable customerTable { get; set; }
    }
}
