//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBookPvt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetailsTable
    {
        public int Id { get; set; }
        public int bookIdFk { get; set; }
        public int bookOrderIdFk { get; set; }
        public Nullable<double> qty { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> totalAmount { get; set; }
    
        public virtual bookOrderTable bookOrderTable { get; set; }
        public virtual bookTable bookTable { get; set; }
    }
}
